# Use the official Node.js image with Alpine Linux as the base
FROM node:alpine

# Set the working directory inside the container
WORKDIR /app

# Copy the Node.js application files
COPY app/package.json ./
COPY app/app.js ./app.js

# Install Node.js dependencies
RUN npm install

# Expose the port that the Node.js application will run on
EXPOSE 4000

# Install necessary packages for Nginx and Lua
RUN apk add --no-cache \
    nginx \
    curl

# Copy custom Nginx configuration
COPY nginx/nginx.conf /etc/nginx/nginx.conf

# Copy your Node.js application into the container
COPY app/package.json .
COPY app/app.js .

# Start both NGINX and Node.js
CMD ["sh", "-c", "nginx && node app.js"]

# Expose ports for Nginx and Node.js
EXPOSE 80
EXPOSE 4000
