# Use the official Node.js Alpine image as the base
FROM node:alpine

# Install necessary packages for Nginx and Lua
RUN apk add --no-cache \
    build-base \
    pcre \
    pcre-dev \
    zlib \
    zlib-dev \
    openssl-dev

RUN wget https://nginx.org/download/nginx-1.27.0.tar.gz && \
    tar zxpf nginx-1.27.0.tar.gz && \
    cd nginx-1.27.0 && \
    ./configure --sbin-path=/usr/bin/nginx --conf-path=/etc/nginx/nginx.conf \
    --error-log-path=/var/log/nginx/error.log --http-log-path=/var/log/nginx/access.log \
    --with-pcre --pid-path=/var/run/nginx.pid \
    --with-http_ssl_module \
    --with-http_auth_request_module && \
    make build && \
    make install

# Create directories for the apps and copy the application code
WORKDIR /api
COPY api /api

WORKDIR /jwt-token-validator
COPY jwt-token-validator /jwt-token-validator

# Install dependencies for both apps
WORKDIR /api
RUN npm install

WORKDIR /jwt-token-validator
RUN npm install

# Copy Nginx configuration file
COPY nginx/nginx.conf /etc/nginx/nginx.conf

# Copy the entrypoint script
COPY entrypoint.sh /entrypoint.sh
RUN chmod +x /entrypoint.sh

# Expose the ports
EXPOSE 80

# Run the entrypoint script
ENTRYPOINT ["/entrypoint.sh"]
