FROM node:alpine

# Install necessary packages
RUN apk add --no-cache \
    nginx \
    lua5.1 \
    lua5.1-socket \
    lua5.1-sec \
    lua5.1-cjson \
    git \
    wget \
    openssl \
    build-base \
    libressl-dev \
    lua5.1-dev \
    tar \
    xz

# Install LuaRocks
RUN wget https://luarocks.org/releases/luarocks-3.9.2.tar.gz && \
    tar zxpf luarocks-3.9.2.tar.gz && \
    cd luarocks-3.9.2 && \
    ./configure && \
    make build && \
    make install && \
    ln -s /usr/local/bin/luarocks /usr/bin/luarocks

# Install Lua modules using LuaRocks
RUN luarocks install lua-resty-http
RUN luarocks install lua-resty-jwt
RUN luarocks install lua-resty-openidc

# Remove default server definition
#RUN rm /etc/nginx/conf.d/default.conf

# Copy NGINX configuration file
COPY nginx/nginx.conf /etc/nginx/nginx.conf

# Copy your Node.js app
WORKDIR /app

COPY app/package.json .
COPY app/app.js .

# Install Node.js dependencies
RUN npm install

# Expose the port that the Node.js app listens on
EXPOSE 4000

# Start both NGINX and Node.js
CMD ["sh", "-c", "nginx && node /app/index.js"]
